package net.mobz.Inits;

import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;

public class Soundinit {

    public static final Identifier AMBIENTTANK = new Identifier("mobz:ambienttank");
    public static SoundEvent AMBIENTTANKEVENT = new SoundEvent(AMBIENTTANK);
    public static final Identifier DEATHTANK = new Identifier("mobz:deathtank");
    public static SoundEvent DEATHTANKEVENT = new SoundEvent(DEATHTANK);
    public static final Identifier HURTTANK = new Identifier("mobz:hurttank");
    public static SoundEvent HURTTANKEVENT = new SoundEvent(HURTTANK);
    public static final Identifier STEPTANK = new Identifier("mobz:steptank");
    public static SoundEvent STEPTANKEVENT = new SoundEvent(STEPTANK);
    public static final Identifier DEATHCREEP = new Identifier("mobz:creepdeath");
    public static SoundEvent DEATHCREEPEVENT = new SoundEvent(DEATHCREEP);
    public static final Identifier SAYCREEP = new Identifier("mobz:creepsay");
    public static SoundEvent SAYCREEPEVENT = new SoundEvent(SAYCREEP);
    public static final Identifier DEATHCRIP = new Identifier("mobz:cripdeath");
    public static SoundEvent DEATHCRIPEVENT = new SoundEvent(DEATHCRIP);
    public static final Identifier SAYCRIP = new Identifier("mobz:cripsay");
    public static SoundEvent SAYCRIPEVENT = new SoundEvent(SAYCRIP);
    public static final Identifier SAYPIG = new Identifier("mobz:pigsay");
    public static SoundEvent SAYPIGEVENT = new SoundEvent(SAYPIG);
    public static final Identifier HURTPIG = new Identifier("mobz:pighurt");
    public static SoundEvent HURTPIGEVENT = new SoundEvent(HURTPIG);
    public static final Identifier DEATHPIG = new Identifier("mobz:pigdeath");
    public static SoundEvent DEATHPIGEVENT = new SoundEvent(DEATHPIG);
    public static final Identifier DEATHEND = new Identifier("mobz:enddeath");
    public static SoundEvent DEATHENDEVENT = new SoundEvent(DEATHEND);
    public static final Identifier ENDHURT = new Identifier("mobz:endhurt");
    public static SoundEvent ENDHURTEVENT = new SoundEvent(ENDHURT);
    public static final Identifier SAYEND = new Identifier("mobz:endsay");
    public static SoundEvent SAYENDEVENT = new SoundEvent(SAYEND);
    public static final Identifier SAYSPEED = new Identifier("mobz:speedsay");
    public static SoundEvent SAYSPEEDEVENT = new SoundEvent(SAYSPEED);
    public static final Identifier STEPSPEED = new Identifier("mobz:speedstep");
    public static SoundEvent STEPSPEEDEVENT = new SoundEvent(STEPSPEED);
    public static final Identifier GOLEMHIT = new Identifier("mobz:golemhit");
    public static SoundEvent GOLEMHITEVENT = new SoundEvent(GOLEMHIT);
    public static final Identifier GOLEMWALK = new Identifier("mobz:golemwalk");
    public static SoundEvent GOLEMWALKEVENT = new SoundEvent(GOLEMWALK);
    public static final Identifier GOLEMDEATH = new Identifier("mobz:golemdeath");
    public static SoundEvent GOLEMDEATHEVENT = new SoundEvent(GOLEMDEATH);
    public static final Identifier SKELIDEATH = new Identifier("mobz:skelideath");
    public static SoundEvent SKELIDEATHEVENT = new SoundEvent(SKELIDEATH);
    public static final Identifier SKELADEATH = new Identifier("mobz:skeladeath");
    public static SoundEvent SKELADEATHEVENT = new SoundEvent(SKELADEATH);
    public static final Identifier SKELIHURT = new Identifier("mobz:skelihurt");
    public static SoundEvent SKELIHURTEVENT = new SoundEvent(SKELIHURT);
    public static final Identifier SKELAHURT = new Identifier("mobz:skelahurt");
    public static SoundEvent SKELAHURTEVENT = new SoundEvent(SKELAHURT);
    public static final Identifier SKELISAY = new Identifier("mobz:skelisay");
    public static SoundEvent SKELISAYEVENT = new SoundEvent(SKELISAY);
    public static final Identifier SKELASAY = new Identifier("mobz:skelasay");
    public static SoundEvent SKELASAYEVENT = new SoundEvent(SKELASAY);
    public static final Identifier SKELISTEP = new Identifier("mobz:skelistep");
    public static SoundEvent SKELISTEPEVENT = new SoundEvent(SKELISTEP);
    public static final Identifier SKELASTEP = new Identifier("mobz:skelastep");
    public static SoundEvent SKELASTEPEVENT = new SoundEvent(SKELASTEP);
    public static final Identifier NOTHING = new Identifier("mobz:nothing");
    public static SoundEvent NOTHINGEVENT = new SoundEvent(NOTHING);
    public static final Identifier ANGRYBATTLEHORN = new Identifier("mobz:angrybattlehorn");
    public static SoundEvent ANGRYBATTLEHORNEVENT = new SoundEvent(ANGRYBATTLEHORN);
    public static final Identifier MEDIVEALSOUND = new Identifier("mobz:medivealsound");
    public static SoundEvent MEDIVEALSOUNDEVENT = new SoundEvent(MEDIVEALSOUND);
    public static final Identifier MEDIVEALSOUND2 = new Identifier("mobz:medivealsound2");
    public static SoundEvent MEDIVEALSOUND2EVENT = new SoundEvent(MEDIVEALSOUND2);
    public static final Identifier EVADEATH = new Identifier("mobz:evadeath");
    public static SoundEvent EVADEATHEVENT = new SoundEvent(EVADEATH);
    public static final Identifier EVAHURT = new Identifier("mobz:evahurt");
    public static SoundEvent EVAHURTEVENT = new SoundEvent(EVAHURT);
    public static final Identifier EVAIDLE = new Identifier("mobz:evaidle");
    public static SoundEvent EVAIDLEEVENT = new SoundEvent(EVAIDLE);
    public static final Identifier EVEDEATH = new Identifier("mobz:evedeath");
    public static SoundEvent EVEDEATHEVENT = new SoundEvent(EVEDEATH);
    public static final Identifier EVEHURT = new Identifier("mobz:evehurt");
    public static SoundEvent EVEHURTEVENT = new SoundEvent(EVEHURT);
    public static final Identifier EVEIDLE = new Identifier("mobz:eveidle");
    public static SoundEvent EVEIDLEEVENT = new SoundEvent(EVEIDLE);
    public static final Identifier ILLUIDLE = new Identifier("mobz:illuidle");
    public static SoundEvent ILLUIDLEEVENT = new SoundEvent(ILLUIDLE);
    public static final Identifier ILLUDEATH = new Identifier("mobz:illudeath");
    public static SoundEvent ILLUDEATHEVENT = new SoundEvent(ILLUDEATH);
    public static final Identifier ILLUHURT = new Identifier("mobz:illuhurt");
    public static SoundEvent ILLUHURTEVENT = new SoundEvent(ILLUHURT);
    public static final Identifier PBITE = new Identifier("mobz:pbite");
    public static SoundEvent PBITEEVENT = new SoundEvent(PBITE);
    public static final Identifier BOARSAY = new Identifier("mobz:boarsay");
    public static SoundEvent BOARSAYEVENT = new SoundEvent(BOARSAY);
    public static final Identifier BOARDEATH = new Identifier("mobz:boardeath");
    public static SoundEvent BOARDEATHEVENT = new SoundEvent(BOARDEATH);
    public static final Identifier WITHDEATH = new Identifier("mobz:withdeath");
    public static SoundEvent WITHDEATHEVENT = new SoundEvent(WITHDEATH);
    public static final Identifier WITHHURT = new Identifier("mobz:withhurt");
    public static SoundEvent WITHHURTEVENT = new SoundEvent(WITHHURT);
    public static final Identifier WITHIDLE = new Identifier("mobz:withidle");
    public static SoundEvent WITHIDLEEVENT = new SoundEvent(WITHIDLE);
    public static final Identifier DARKIDLE = new Identifier("mobz:darkidle");
    public static SoundEvent DARKIDLEEVENT = new SoundEvent(DARKIDLE);
    public static final Identifier DARKDEATH = new Identifier("mobz:darkdeath");
    public static SoundEvent DARKDEATHEVENT = new SoundEvent(DARKDEATH);
    public static final Identifier DARKHIT = new Identifier("mobz:darkhit");
    public static SoundEvent DARKHITEVENT = new SoundEvent(DARKHIT);
    public static final Identifier WHURT = new Identifier("mobz:whurt");
    public static SoundEvent WHURTEVENT = new SoundEvent(WHURT);
    public static final Identifier WDEATH = new Identifier("mobz:wdeath");
    public static SoundEvent WDEATHEVENT = new SoundEvent(WDEATH);
    public static final Identifier WGROWL = new Identifier("mobz:wgrowl");
    public static SoundEvent WGROWLEVENT = new SoundEvent(WGROWL);

    public static void init() {

        Registry.register(Registry.SOUND_EVENT, Soundinit.AMBIENTTANK, AMBIENTTANKEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.DEATHTANK, DEATHTANKEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.HURTTANK, HURTTANKEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.STEPTANK, STEPTANKEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.DEATHCREEP, DEATHCREEPEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SAYCREEP, SAYCREEPEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.DEATHCRIP, DEATHCRIPEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SAYCRIP, SAYCRIPEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SAYPIG, SAYPIGEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.HURTPIG, HURTPIGEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.DEATHPIG, DEATHPIGEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.DEATHEND, DEATHENDEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.ENDHURT, ENDHURTEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SAYEND, SAYENDEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SAYSPEED, SAYSPEEDEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.STEPSPEED, STEPSPEEDEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.GOLEMDEATH, GOLEMDEATHEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.GOLEMHIT, GOLEMHITEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.GOLEMWALK, GOLEMWALKEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SKELADEATH, SKELADEATHEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SKELAHURT, SKELAHURTEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SKELASAY, SKELASAYEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SKELASTEP, SKELASTEPEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SKELIDEATH, SKELIDEATHEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SKELIHURT, SKELIHURTEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SKELISAY, SKELISAYEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.SKELISTEP, SKELISTEPEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.NOTHING, NOTHINGEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.ANGRYBATTLEHORN, ANGRYBATTLEHORNEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.MEDIVEALSOUND, MEDIVEALSOUNDEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.MEDIVEALSOUND2, MEDIVEALSOUND2EVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.EVADEATH, EVADEATHEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.EVAHURT, EVAHURTEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.EVAIDLE, EVAIDLEEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.EVEDEATH, EVEDEATHEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.EVEHURT, EVEHURTEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.EVEIDLE, EVEIDLEEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.ILLUIDLE, ILLUIDLEEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.ILLUDEATH, ILLUDEATHEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.ILLUHURT, ILLUHURTEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.PBITE, PBITEEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.BOARSAY, BOARSAYEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.BOARDEATH, BOARDEATHEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.WITHDEATH, WITHDEATHEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.WITHHURT, WITHHURTEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.WITHIDLE, WITHIDLEEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.DARKDEATH, DARKDEATHEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.DARKHIT, DARKHITEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.DARKIDLE, DARKIDLEEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.WHURT, WHURTEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.WGROWL, WGROWLEVENT);
        Registry.register(Registry.SOUND_EVENT, Soundinit.WDEATH, WDEATHEVENT);
    }

}